#!/bin/bash
# Hook: PostToolUse - Detect errors, collect context, instruct LLM
#
# This hook intercepts tool output, detects error patterns, and instructs
# the LLM to load the error-handling skill for structured analysis.
#
# Part of the Reversed Hook Architecture:
# 1. Hook detects errors (simple pattern matching)
# 2. Hook collects context and STOPS execution
# 3. Hook instructs LLM to load error-handling skill
# 4. Error-handling skill takes over with full LLM capabilities
#
# Installation: Copy to .claude/hooks/ or configure in settings.json with full path

RESULT=$(cat)
TOOL_NAME="${CLAUDE_TOOL_NAME:-unknown}"
TIMESTAMP=$(date -Iseconds)

# Find project root by searching for .plan directory
# Start from current directory and search upward
find_project_root() {
    local dir="$PWD"
    while [[ "$dir" != "/" ]]; do
        if [[ -d "$dir/.plan" ]]; then
            echo "$dir"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    # Fallback: use current directory
    echo "$PWD"
}

PROJECT_ROOT="$(find_project_root)"
ERROR_CONTEXT_FILE="${PROJECT_ROOT}/.plan/error-context.toon"

# Ensure .plan directory exists
mkdir -p "${PROJECT_ROOT}/.plan"

# Simple error pattern detection
# Matches: status: error, exit code N (where N > 0), Unknown skill, not found, failed, exception
if echo "$RESULT" | grep -qiE "(status[[:space:]]*:[[:space:]]*error|exit code [1-9]|Unknown skill|skill not found|not found|failed|exception)"; then

    # Extract error patterns matched (first 3 unique matches)
    PATTERNS=$(echo "$RESULT" | grep -oiE "(status[[:space:]]*:[[:space:]]*error|exit code [1-9]|Unknown skill|skill not found|not found|failed|exception)" | head -3 | tr '\n' ',' | sed 's/,$//')

    # Collect context into TOON file (token-efficient format)
    cat > "$ERROR_CONTEXT_FILE" << EOF
# Error Context
# Generated by error-detector hook
# Format: TOON (Token-Oriented Object Notation)

timestamp: "$TIMESTAMP"
tool: "$TOOL_NAME"
working_directory: "$(pwd)"

error:
  patterns_matched: "$PATTERNS"
  blocking: true

raw_output: |
$(echo "$RESULT" | sed 's/^/  /')
EOF

    # Return instruction for LLM
    cat << 'EOF'
## ERROR DETECTED - EXECUTION STOPPED

An error was detected in tool output. Context saved to `.plan/error-context.toon`.

**REQUIRED ACTION**: Load the error-handling skill to analyze and proceed:

```
Skill: cui-plugin-development-tools:error-handling
```

The skill will:
1. Read error context from `.plan/error-context.toon`
2. Perform root cause analysis
3. Present options to user
4. Wait for decision before continuing

DO NOT proceed with other actions until error is handled.
EOF

    exit 1  # Block further execution
fi

exit 0
